- ephemeris/get_tool_list_from_galaxy.py
This may be useful for deployers wishing to replicate a server,
or for tracking the currently installed tool list in a VCS.
> Add script for generating tool_list.yml from galaxy instances

- ephemeris/get_tool_list_from_galaxy.py
- ephemeris/shed_install.py
- Use bioblend keyword arguments, this should help prevent the problem in https://github.com/galaxyproject/ansible-galaxy-tools/pull/34
- Better checks and error messages when an invalid tool has been specified
- Flip the install_tool_dependencies switch to skip_tool_dependencies, so that by default classic toolshed packages will be used
- Add an option to skip the changeset revision retrieved from an existing galaxy instance. This list could be used to update all installed tools (Except that we specifically skip tools that are already installed ...)
This addresses #9, #10 and #13
> More robust shed-install script, install dependencies by default, improve logging

- ephemeris/shed_install.py
When Galaxy is setup behind a proxy, the reported message is different than the Galaxy-default so be much more permissive in determining when a tool installation is taking a while.
> Be more generic in determining a server time-out

- ephemeris/shed_install.py
This PR will enable global options in a tool yaml files. Means 
```
install_repository_dependencies: true
install_resolver_dependencies: true
install_tool_dependencies: false
```
can be specified as top arguments next to the Galaxy instance and API key. It will also change the default setting, to install resolver-dependencies and not tool-dependencies anymore.
> enable global options in a tool yaml file

- HISTORY.rst
- ephemeris/__init__.py
- ephemeris/run_data_managers.py
- ephemeris/run_data_managers.yaml.sample
- setup.py
This scripts let you define some data managers with different `items` and parameters to populate Galaxy instances like Galaxy flavors.
> Run data managers

- ephemeris/run_data_managers.py
It seems that the current setup.py setup needs to have a clean main() function.
Anyone know what is the preferred Python way to handle such a setup? I have seen many projects that writes the `bin/*` on there own.
> Clean up the main() function

- ephemeris/generate_tool_list_from_ga_workflow_files.py
- test.sh
- tests/test_workflow_2.ga
with a nasty trick to preserve a more readable order of keys in the yml file (name first)
install_resolver_dependencies is always set to True
> install_resolver_dependencies keys are printed in the tool_list.yml

- ephemeris/sleep.py
- setup.py
Lots of the flavour images do a `startup_lite && sleep 30 && ...` in order to do things on a live database. This number can be quite variable. 30s was fine for me, but wasn't for a colleague who had to increase it.
This script can be used in place of `sleep 30` and will sleep until `/api/version` is available. This *should* be much more reliable.
A timeout option is provided to prevent abusing build resources if something else is at fault (e.g. a missing package allowed startup_lite to succeed initially but fail silently later).
> Add sleep script

- ephemeris/run_data_managers.py
run_data_managers has an -a or --api-key flag inherited from common args but did not allow for using the api_key.
> Enable api key on run_data_managers

- ephemeris/run_data_managers.py
Below error was generated when running run-data-managers. I suppose this was because the galaxy url was not properly prepended to the /api part. With this fix the problem seems to be solved.
> Traceback (most recent call last):
>   File "/usr/local/bin/run-data-managers", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/ephemeris/run_data_managers.py", line 80, in main
>     run_dm(args)
>   File "/usr/local/lib/python2.7/dist-packages/ephemeris/run_data_managers.py", line 62, in run_dm
>     gi.make_get_request(urljoin(url, 'api/tool_data/%s/reload' % data_table))
>   File "/usr/local/lib/python2.7/dist-packages/bioblend/galaxyclient.py", line 88, in make_get_request
>     r = requests.get(url, **kwargs)
>   File …
> fix error in run_data_managers

- ephemeris/run_data_managers.py
Sometimes no items are needed for run-data-managers, see the following file:
```YAML
data_managers:
- id: all_fasta_by_path_manager
params:
- 'dbkey': 'GRCh38/hg38'
- 'name': 'Human Genome Assembly GRCh38/hg38'
- 'path': '/export/genomes/hg38.fa'
data_table_reload:
- all_fasta
- __dbkeys__
```
However, run-data-managers throws the following error when the file is run:
```
File "/home/ruben/ephemeris/.venv/bin/run-data-managers", line 11, in <module>
load_entry_point('ephemeris==0.6.2.dev0', 'console_scripts', 'run-data-managers')()
File "/home/ruben/ephemeris/.venv/lib/python2.7/site-packages/ephemeris-0.6.2.dev0-py2.7.egg/ephemeris/run_data_managers.py", line 80, in main
run_dm(args)
File "/home/ruben/ephemeris/.venv/lib/python2.7/site-packages/ephemeris …
```
> Fixed empty items list issue

- ephemeris/run_data_managers.py
- ephemeris/shed_install.py
- ephemeris/sleep.py
- requirements.txt
- tests/run_data_managers.yaml.test
- tests/test.sh
fixes #54 
~~The stdout of run-data-managers is not up to scratch though. It does not give any output. If the -v flag is used, it gives too much output (also debug messages). Can somebody show me how to get run-data-managers too display all the info messages in stdout?~~
> Parallelization of run-data-managers. Add galaxy-wait to tests. Fix galaxy-wait issue with nginx.

- ephemeris/shed_tools.py
> safeguard revisions

- ephemeris/workflow_install.py
Allows immediate publishing of loaded workflows.
> Makes publishing of imported workflows available.

- ephemeris/__init__.py
- ephemeris/get_tool_list_from_galaxy.py
- ephemeris/run_data_managers.py
- ephemeris/setup_data_libraries.py
- ephemeris/shed_tools.py
- scripts/test_wheel.bash
- tests/test.sh
Hi. This solves #69 .
Have not run extensive testing yet, but will do that tomorrow.
It seems to run for now. Curious to see your feedback.
One of the side effects is that `get-tool-list` now also uses `get_galaxy_connection` method. a nice step towards unifying ephemeris.
EDIT:
Changes:
- `shed-tools update` now also updates data managers.
- With `get-tool-list` you can now also get all installed data managers, provided you have admin access to the galaxy.
> Also update data managers

- ephemeris/run_data_managers.py
- tests/data_manager_list.yaml
- tests/run_data_managers.yaml.test
- tests/test.sh
- tests/test_library.sh
- tests/test_run_data_managers.sh
- tests/test_shed_tools.sh
- tests/test_workflow_and_data.sh
- tests/tool_list.yaml.sample
While installing a few reference genomes on my galaxy I got annoyed by the indexing steps. These take quite a long time. And `run-data-managers` only runs one data manager at a time. I feel that job scheduling should be handled by Galaxy and not by `run-data-managers` so I changed the way that `run-data-managers` submits jobs.
Now `run-data-managers` first picks all the data managers that populate source tables (DEFAULT: ["all_fasta"]). Since other data managers depend on these tables. Then it runs them. After that it runs _all_ the other data managers. Let galaxy figure out to schedule all these jobs. 
This provides a significant speedup when you're adding a vertebrate genome to the list. Instead of watching your bowtie and bwa indexes be created one after another, they are now created …
> Run data managers aggressive parallelization and refactoring.

- ephemeris/common_parser.py
- ephemeris/ephemeris_log.py
- ephemeris/run_data_managers.py
- ephemeris/shed_tools.py
> Fix hardcoded  log paths.

- ephemeris/get_tool_list_from_galaxy.py
- ephemeris/shed_tools.py
- requirements.txt
Builds on #78 from @rhpvorderman since it modifies similar files.
While it does run the tests and produce a JSON output file that should be usable with ``planemo test_reports`` (http://planemo.readthedocs.io/en/latest/commands.html#test-reports-command) after the next Planemo release, marked as WIP because:
Also, what of these questions can we delay to a second iteration?
Implements https://github.com/galaxyproject/ephemeris/issues/76.
> Option to test tools on update/install for Galaxy 18.05.

- ephemeris/generate_tool_list_from_ga_workflow_files.py
- ephemeris/setup_data_libraries.py
- ephemeris/shed_tools.py
- setup.cfg
- tests/library_data_example.yaml
- tests/library_data_example_legacy.yaml
- tests/test_workflow_and_data.sh
Will convert older style library YAML format from ephemeris to modern version, will attempt to implement a subset of the modern format with legacy APIs as needed.
Some of the defaults that only made sense for training data have been hidden behind a new ``--training`` flag.
> Upload 2.0 support for data library creation.

- ephemeris/shed_tools.py
I was frequently getting stuff like this:
```pytb
(ephemeris)nate@weyerbacher% shed-tools install -t diffbind-upgrade.yaml -g https://test-installer.galaxyproject.org/ -v
Storing log file in: /tmp/ephemeris_pPBMw4
(1/1) Installing repository diffbind from bgruening to section "peak_calling" at revision c97a786e8fb5 (TRT: 0:00:58.435025)
Timeout during install of diffbind, extending wait to 1h
File "/home/nate/.virtualenvs/ephemeris/bin/shed-tools", line 11, in <module>
sys.exit(main())
File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 937, in main
install_tool_manager.install_repositories()
File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 728, …
```
> Catch failures on requests to the installed repo list when doing post-timeout spinning on installation in shed-tools

- tox.ini
Apparently the setup was not working. It appears that codacy needs to know the exact path of the source files for coverage to work. By contrast, coverage with pytest in a tox environment only works when the package site is used to determine coverage. 
Luckily `sed` can rescue us in this case.
I've tested this manually, and coverage reports are accepted now.
> fix coverage reporting on codacy

- src/ephemeris/get_tool_list_from_galaxy.py
When tool_with_panel was empty and ToolSheedClient.get_repositories() was not it was crashing because tool_panel_section_id/label were not defined. Fix : Define them outside of the loop to match the use later inside the if condition.
Make a new branch/pull request because inside the other one there was a mysterious anoying sticky white space inserted.
> Fix crash when too_with_panel is empty

- src/ephemeris/common_parser.py
This tripped me up when trying to use the `shed-tools install` command. I entered `-u rdvelazquez` which is my public user name on the instance but the command failed. I had to enter `-u <my email address>` for the command to work.
> Update Docs for User Name (Should be Email)

- src/ephemeris/get_tool_list_from_galaxy.py
- src/ephemeris/shed_tools.py
I don't really know what I'm doing here, but following @mvdbeek suggestion :-).
> Handle timeout gracefully for UWSGI connection

- requirements.txt
- src/ephemeris/shed_tools.py
- src/ephemeris/shed_tools_args.py
- tests/test_shed_tools.py
~~We'll need a galaxy-lib update with https://github.com/galaxyproject/galaxy/pull/7167 for re-using the history.~~
We've got a new galaxy-lib update, so let's get this in. It allows testing tools without an admin API key and without a shared filesystem.
> Test tools in parallel, with regular user permissions, without a shared filesystem

- src/ephemeris/shed_tools_args.py
the `parallel_tests` also does not render in docs, not sure why yet
> fix default for 'parallel_tests' typo

- src/ephemeris/shed_tools.py
requests.exceptions.ConnectionError Exceptions don't have a body
attribute, but bioblend's ConnectionError `__str__` includes
the body:
```
def __str__(self):
return "{0}: {1}".format(self.args[0], self.body)
```
> Fix default message check

- src/ephemeris/shed_tools.py
That was useful for figuring out
```
Test 'toolshed.g2.bx.psu.edu/repos/iuc/mothur_unifrac_weighted/mothur_unifrac_weighted/1.39.5.0-0' failed
File "/var/jenkins/shiningpanda/jobs/35ce1600/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ephemeris/shed_tools.py", line 338, in run_test
register_job_data=register, quiet=True, test_history=test_history,
File "/var/jenkins/shiningpanda/jobs/35ce1600/virtualenvs/d41d8cd9/lib/python3.5/site-packages/galaxy/tools/verify/interactor.py", line 733, in verify_tool
stage_data_in_history(galaxy_interactor, tool_id, testdef.test_data(), history=test_history, force_path_paste=force_path_paste)
File "/var/jenkins/shiningpanda/jobs/35ce1600/virtualenvs/d41d8cd9/lib/python3.5/site-packages/galaxy/tools/verify/interactor.py …
```
> Print exception when unexpected test failure is caught

- src/ephemeris/shed_tools.py
That might happen with invalid test sections or other
Galaxy bugs.
> Don't raise exception when tool tests can't be fetched

- src/ephemeris/setup_data_libraries.py
- supports legacy + non
- if legacy, fetches a list of all upload1 jobs and check states of those in a loop
- if normal, now checks the actual upload job that was scheduled.
> Data library creation would hang forever if you had a single non-ok command ever

- src/ephemeris/shed_tools.py
Otherwise any version of the repo that's already installed and encountered first in the loop will cause the poll to immediately return success.
> When polling for repo install status, ensure the correct revision is being checked

- src/ephemeris/setup_data_libraries.py
A little fix for setup_data_libraries in legacy mode: folders' descriptions were not passed to galaxy
ping @bgruening
> setup_data_libraries: pass description when creating folders

- src/ephemeris/shed_tools.py
- src/ephemeris/sleep.py
Fixes https://github.com/galaxyproject/ephemeris/issues/148.
> Cast exceptions to string using unicodify

- src/ephemeris/generate_tool_list_from_ga_workflow_files.py
- src/ephemeris/get_tool_list_from_galaxy.py
The `tool_shed` URLs returned by Galaxy via `get_tool_panel()` don't have a protocol part, while the `tool_shed_url` field in YAML files generated by `workflow-to-tools` start with an `https://` . This resulted in testing 0 tools when `shed_tools` is invoked on such a YAML file.
> Fix `shed-tools test -t workflow_tools.yml`

- src/ephemeris/shed_tools.py
This fixes https://github.com/galaxyproject/ephemeris/issues/153.
> Wait for the correct repository

- src/ephemeris/get_tool_list_from_galaxy.py
- src/ephemeris/shed_tools.py
- src/ephemeris/shed_tools_args.py
When shed-tools looks for tests, it looks for tool ids within the output of get_tool_panel.  There is generally only one version of a tool in the panel but there could be several versions of the tool installed.  I'd like to be able to run tests for older revisions of tools.  Currently if the --revisions arg does not correspond to the version in the panel, no tests are run.
My proposed change is to look in the output of get_tools instead of get_tool_panel if the revision is provided.
I'm not sure what should happen when there is no changeset revision - I've defaulted using get_tool_panel in this case to look for what is usually the most recent version, but I could change this so that it runs tests from all versions.
Catherine, Galaxy Australia
> get all tools when searching for tool ids for testing (get_tools instead of get_tool_panel)

- .github/workflows/ci.yaml
- .travis.yml
- Makefile
- README.rst
- dev-requirements.txt
- requirements.txt
- setup.py
- src/ephemeris/shed_tools.py
- src/ephemeris/shed_tools_args.py
- src/ephemeris/sleep.py
- tests/docker_for_galaxy.py
- tests/test.sh
- tests/test_library.sh
- tests/test_run_data_managers.py
- tests/test_shed_tools.sh
- tests/test_workflow_and_data.sh
- tox.ini
- Migrate most testing and linting to Github actions.
- Bring in the latest changes to sleep function from Planemo.
- Update sleep to allow waiting for a key to become an admin key (new Docker container is way different, the web server becomes active before the key works and the key works before it is an admin key). 😅 
- Update tests for changes to docker API key and admin user password.
- Bring in client configuration tests from my last PR.
- Drop Python 2.7 and 3.5 support.
> Various updates to testing and CI infrastructure.

- src/ephemeris/generate_tool_list_from_ga_workflow_files.py
workflow-to-tools currently skips any tools in subworkflows.  This adds a recursive step to go through the steps in subworkflows.
> workflow-to-tools: get tools from subworkflows

- .github/workflows/ci.yaml
- requirements.txt
- setup.py
- src/ephemeris/set_library_permissions.py
- tox.ini
I added a tool to set the permissions of ALL datasets in a given data library (in folders and subfolders) at once to the given roles.
It is a workaround for one point of this [Issue](https://github.com/galaxyproject/galaxy/issues/15007), I created.
Usage:
```
usage: set_library_permissions [-h] [-v] [-g GALAXY] [-u USER] [-p PASSWORD] [-a API_KEY] [--library LIBRARY] [--roles ROLES]
```
Currently the default loglevel is INFO. I don't have experience with this so please tell me if I should change it.
> Set Library Permissions

- setup.py
We have one new command waiting for a release (`set-library-permissions`) that was documented as using `-` in the CLI examples, and then `install-tool-deps` which used `_`, and now gets an alias for `-`
> Standardize CLI commands on - instead of _

- src/ephemeris/setup_data_libraries.py
- BioBlend [Release 1.1.0 ](https://github.com/galaxyproject/bioblend/commit/bdf7a10e37e505ac46b3480083d751b021fc208b)made the following change 
```
- Using the deprecated ``folder_id`` parameter of the
``LibraryClient.get_folders()`` method now raises a ``ValueError``
exception."
```
- Therefore when the `setup-data-libraries` command is run ephemeris fails with the error message.
```
+ setup-data-libraries -g https://galaxy-example.org -a key --training -i /libraries/example-library.yaml --legacy
Library name: Mouse sequencing project
File "/usr/local/bin/setup-data-libraries", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.10/dist-packages/ephemeris/setup_data_libraries.py", line 214, in main
setup_data_libraries(gi, args.infile, …
```
> Remove folder id from get_folders function call in setup-data-libraries

- src/ephemeris/common_parser.py
- src/ephemeris/generate_tool_list_from_ga_workflow_files.py
- src/ephemeris/get_tool_list_from_galaxy.py
- src/ephemeris/install_tool_deps.py
- src/ephemeris/run_data_managers.py
- src/ephemeris/set_library_permissions.py
- src/ephemeris/setup_data_libraries.py
- src/ephemeris/shed_tools_args.py
- src/ephemeris/sleep.py
- src/ephemeris/workflow_install.py
This converts all ephemeris command flags that use underscores to dashes instead. Underscores continue to be supported but are hidden from the help text.
Underscores in UNIX command line flags are pretty non-standard, and are way more painful to type, to boot.
Also, entry points for `install-tool-deps` and `set-library-permissions` are installed in addition to their original underscore versions. The underscore versions of these two commands should be considered deprecated maybe be removed at some point, but the underscore flags can be kept indefinitely with little harm.
> Prefer dashes instead of underscores in flags

- .readthedocs.yaml
Docs builds currently fail with:
```
Problem in your project's configuration. No default configuration file found at repository's root. See https://docs.readthedocs.io/en/stable/config-file/
```
See e.g. https://readthedocs.org/projects/ephemeris/builds/22831168/
> Add now mandatory readthedocs config file

- setup.py
- src/ephemeris/__init__.py
- src/ephemeris/_config_models.py
- src/ephemeris/_idc_data_managers_to_tools.py
- src/ephemeris/_idc_lint.py
- src/ephemeris/_idc_split_data_manager_genomes.py
- src/ephemeris/common_parser.py
- src/ephemeris/run_data_managers.py
- src/ephemeris/shed_tools.py
- tests/test_idc_data_managers_to_tools.py
- tests/test_idc_lint.py
- tests/test_setup_data_libraries_cli.py
- tests/test_shed_tools_cli.py
- tests/test_split_genomes.py
- tests/test_workflow_install_cli.py
- More unit tests.
- Add option of filtering by stage (and other things) in split script.
- More validation of generated artifacts (in particular tools YAML).
- More checks in the IDC lint (verify all reference indexers in genomes.yml are keyed in data_managers.yml and all data manager tools are from the main tool shed).
> Enhancements to the IDC scripts

- src/ephemeris/_config_models.py
For compatibility with pydantic 2. Also makes description optional, since it can be set when using ucsc source.
> Use None default value where items are optional
