- ephemeris/generate_tool_list_from_ga_workflow_files.py
ping @jmchilton 
As promised here is the script that generates a yml list of tools from one or several .ga workflow files
> generate_tool_list_from_ga_workflow_files.py

- ephemeris/get_tool_list_from_galaxy.py
as per https://github.com/galaxyproject/ansible-galaxy-tools/issues/35
> tool_panel_section_name --> tool_panel_section_label

- ephemeris/get_tool_list_from_galaxy.py
- tests/tool_list.yaml.sample
for issue https://github.com/galaxyproject/ephemeris/issues/15
> Sample tool list

- ephemeris/get_tool_list_from_galaxy.py
- ephemeris/shed_install.py
- setup.py
- tool_shed_url will have a trailing slash added
- add https if tool_shed_url doesn't list protocol
- get-tool-list entrypoint
Ping @jmchilton
> Get tool list entrypoint and improvements

- ephemeris/library_data_example.yaml
- ephemeris/setup_data_libraries.py
I would like to ship this inside our Docker container so we can use this to get training data into training instances during build time.
> Add a script to populate data libraries

- ephemeris/generate_tool_list_from_ga_workflow_files.py
- ephemeris/get_tool_list_from_galaxy.py
- ephemeris/shed_install.py
- ephemeris/workflow_install.py
> Mention mimum required galaxy versions

- ephemeris/generate_tool_list_from_ga_workflow_files.py
- setup.py
This tool was also missing from the install.
> workflow-to-tools

- ephemeris/setup_data_libraries.py
- setup.py
setup-data-libraries was not installed.
> Setup data libraries

- ephemeris/setup_data_libraries.py
We need to refactor all tools and share options at some point. For now this hack should work.
> Adding more options to setup_data_libraries

- docs/commands.rst
- docs/commands/sleep.rst
- docs/index.rst
> Documentation of sleep command

- CONTRIBUTING.rst
- docs/commands.rst
- docs/commands/galaxy-wait.rst
- docs/commands/get-tool-list.rst
- docs/commands/setup-data-libraries.rst
- docs/commands/sleep.rst
- docs/commands/workflow-install.rst
- docs/commands/workflow-to-tools.rst
- ephemeris/generate_tool_list_from_ga_workflow_files.py
- ephemeris/get_tool_list_from_galaxy.py
- ephemeris/setup_data_libraries.py
- ephemeris/sleep.py
- ephemeris/workflow_install.py
Also added some information on how to contribute documentation (also for new tools).
The descriptions are a bit generic, but now at least all tools are in the documentation.
> Completed tool documentation

- ephemeris/__init__.py
Should fix https://github.com/galaxyproject/ephemeris/issues/56
> Fix unbounded variable

- ephemeris/get_tool_list_from_galaxy.py
- ephemeris/run_data_managers.py
- ephemeris/shed_install.py
- ephemeris/sleep.py
- ephemeris/workflow_install.py
To reflect changes made in #53
> more example files for run-data-managers

- tests/test.sh
- tests/tool_list.yaml.sample
by specifying a newer changeset revision.
>  Add test that demonstrates that tools can be updated

- dev-requirements.txt
- docs/conf.py
fixes issue in #65 
Use latest sphinx-argparse
> fixes verbosity flag issue

- ephemeris/shed_tools.py
> Shed-tools update does not complain about a tool_yaml file

- HISTORY.rst
- ephemeris/__init__.py
- scripts/bootstrap_history.py
Add planemo script to turning Github PRs and Issues into HISTORY.rst content (was already referenced in the Makefile).
> Prepare 0.9.0.

- setup.py
- src/ephemeris/install_tool_deps.py
> Fix typo and add entry point

- scripts/bootstrap_history.py
- scripts/commit_version.py
- scripts/new_version.py
Ran into this:
```
Test 'toolshed.g2.bx.psu.edu/repos/iuc/dropletutils/dropletutils/1.2.1+galaxy6-1' failed
File "/home/ubuntu/tools-venv/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/home/ubuntu/tools-venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
raise err
File "/home/ubuntu/tools-venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 65, in create_connection
sock = socket.socket(af, socktype, proto)
File "/usr/lib/python3.6/socket.py", line 144, in __init__
_socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
During handling of the above exception, another …
```
> Close files

- src/ephemeris/sleep.py
These lines might have been left in by accident.
> delete the extra random sleep lines from sleep.py

- src/ephemeris/_config_models.py
- src/ephemeris/_idc_data_managers_to_tools.py
- src/ephemeris/_idc_split_data_manager_genomes.py
- src/ephemeris/generate_tool_list_from_ga_workflow_files.py
- src/ephemeris/set_library_permissions.py
- src/ephemeris/shed_tools.py
- src/ephemeris/shed_tools_methods.py
https://github.com/galaxyproject/ephemeris/pull/221 plus fix for pydantic 2
> Fix pydantic 2.0 compat
